### ISSUE TITLE
Issues in server.py

### ISSUE THREAD

**Issue by AYESDIE** [AYESDIE/ApertER-API#2]
server.py doesn't seem to be able to access the model it needs to Detect emotions.

**Comment by mohit2agrawal** [comment]
newmoon.py is missing from the branch `master`

**Comment by AYESDIE** [comment]
I renamed alot of files here, newmoon.py must be here but with some other name.

**Comment by mohit2agrawal** [comment]
Yes, its aperter.py. In this case, the master branch would not work, because we are importing from `newmoon`, and not `aperter`.
Also, the `data/CNN.h5` is not available on the `master` branch.

EDIT:
and `data/dataset.py` is also not available. Is there some other method which downloads this from somewhere else?

**Comment by AYESDIE** [comment]
Thanks for finding the issue there.

You will have to get `fer2013.csv` from the internet and make a model yourself using `model.py`, and save the model as `data/CNN.h5` in there.

ALSO: The CNN model used in `model.py` is not up to date. It is not being updated here for some reasons. 
Use that at your own risk.
